manifest:
  version: '0.10'
  remotes:
  - name: rnl
    url-base: https://github.com/rednodelabs
  - name: ncs
    url-base: https://github.com/nrfconnect
  defaults:
    remote: rnl
  projects:
  - name: nrf
    repo-path: sdk-nrf
    remote: ncs
    revision: v1.8.0
    import:
      name-blocklist:
      - zephyr
      - openthread
  - name: zephyr
    revision: nrfconnect/v0.9.11
    import:
      name-allowlist:
      - canopennode
      - civetweb
      - cmsis
      - edtt
      - fatfs
      - hal_nordic
      - hal_st
      - libmetal
      - littlefs
      - loramac-node
      - lvgl
      - lz4
      - mbedtls
      - mcumgr
      - mipi-sys-t
      - nanopb
      - net-tools
      - nrf_hw_models
      - open-amp
      - segger
      - tinycbor
      - tinycrypt
      - TraceRecorderSource
  - name: openthread
    revision: zephyrproject-rtos/v0.9.6
    path: modules/lib/openthread
  - name: rednodebus-release
    revision: v0.9.12
  self:
    path: rednodebus-samples
